version: '3.8'

networks:
  proxy:
    external: true
    name: proxy

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    volumes:
      - ..:/workspace:cached

    command: sleep infinity

    labels:
      - traefik.enable=true
      - traefik.http.routers.enableops-website.rule=Host(`web.enableops.lol`)
      - traefik.http.routers.enableops-website.tls=true
      - traefik.http.routers.enableops-website.entrypoints=web,web-secure,debug
      - traefik.http.services.enableops-website.loadbalancer.server.port=3000

    networks:
      - proxy
